name: download

on:
  push:

env:
  NB_KERNEL: python
  NMA_REPO: course-content
  NMA_MAIN_BRANCH: main

jobs:

  download_videos:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install CI tools
        run: |
          BRANCH=$NMA_MAIN_BRANCH
          wget https://github.com/NeuromatchAcademy/nmaci/archive/refs/heads/$BRANCH.tar.gz
          tar -xzf $BRANCH.tar.gz
          pip install -r nmaci-$BRANCH/requirements.txt
          mv nmaci-$BRANCH/scripts/ ci/
          # FIXME: Remove when PR is merged
          cp extract_links.py ci
          rm -r nmaci-$BRANCH
          rm -r $BRANCH.tar.gz
          echo ci/ >> .gitignore

      - name: Copy tutorials from precourse repo
        run: |
          BRANCH=$NMA_MAIN_BRANCH
          wget https://github.com/NeuromatchAcademy/precourse/archive/refs/heads/$BRANCH.tar.gz
          tar -xzf $BRANCH.tar.gz
          mv precourse-$BRANCH/tutorials/W0D* tutorials/
          cat precourse-main/tutorials/materials.yml tutorials/materials.yml > out.yml
          mv out.yml tutorials/materials.yml
          mv precourse-$BRANCH/prereqs .
          rm -r precourse-$BRANCH
          rm -r $BRANCH.tar.gz

      - name: Extract links
        run: |
          ln -s ../tutorials book/tutorials
          ln -s ../projects book/projects
          ln -s ../prereqs book/prereqs
          python ci/extract_links.py --noyoutube $(find -L book -name '*.ipynb') > links.json

      - name: Install tools
        run: |
          wget --tries=3 https://youtube-dl.org/downloads/latest/youtube-dl -O youtube-dl
          chmod u+x youtube-dl
          sudo apt -y install jq

      - name: Download videos
        run: |
          mkdir videos  
          jq -r ".videos | to_entries | map(.value) | flatten | .[]" links.json | sort | uniq > video_urls.txt
          echo "Downloading videos from these urls"
          cat video_urls.txt
          ./youtube-dl --max-downloads 2 --newline -a video_urls.txt -o "videos/%(title)s.%(ext)s" || echo "Continue"

      - name: Upload videos
        uses: actions/upload-artifact@v3
        with:
          name: NMA-compneuro-videos
          path: videos

  download_slides:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install CI tools
        run: |
          BRANCH=$NMA_MAIN_BRANCH
          wget https://github.com/NeuromatchAcademy/nmaci/archive/refs/heads/$BRANCH.tar.gz
          tar -xzf $BRANCH.tar.gz
          pip install -r nmaci-$BRANCH/requirements.txt
          mv nmaci-$BRANCH/scripts/ ci/
          # FIXME: Remove when PR is merged
          cp extract_links.py ci
          rm -r nmaci-$BRANCH
          rm -r $BRANCH.tar.gz
          echo ci/ >> .gitignore

      - name: Copy tutorials from precourse repo
        run: |
          BRANCH=$NMA_MAIN_BRANCH
          wget https://github.com/NeuromatchAcademy/precourse/archive/refs/heads/$BRANCH.tar.gz
          tar -xzf $BRANCH.tar.gz
          mv precourse-$BRANCH/tutorials/W0D* tutorials/
          cat precourse-main/tutorials/materials.yml tutorials/materials.yml > out.yml
          mv out.yml tutorials/materials.yml
          mv precourse-$BRANCH/prereqs .
          rm -r precourse-$BRANCH
          rm -r $BRANCH.tar.gz

      - name: Extract links
        run: |
          ln -s ../tutorials book/tutorials
          ln -s ../projects book/projects
          ln -s ../prereqs book/prereqs
          python ci/extract_links.py --noyoutube $(find -L book -name '*.ipynb') > links.json

      - name: Install tools
        run: |
          sudo apt -y install jq

      - name: Download slides
        run: |
          mkdir slides
          jq -r "def output: \"-O \" + .value + \" \" +.key; .slides | to_entries | map(output) | .[]" links.json > slide_urls.txt
          cd slides
          while read url; do echo wget --quiet $url; wget --quiet $url; done < ../slide_urls.txt

      - name: Get update date
        id: last_update
        run: |
          last_update=$(echo ${{ github.event.repository.pushed_at}} | cut -c -10)
          echo "last_update=$last_update" >> $GITHUB_OUTPUT

      - name: Upload slides
        uses: actions/upload-artifact@v3
        with:
          name: NMA-compneuro-slides-${{steps.last_update.outputs.last_update}}
          path: slides
