name: publish-book

on: 

  workflow_dispatch:

env:
  NB_KERNEL: python
  NMA_REPO: course-content
  NMA_MAIN_BRANCH: main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: true
          ref: ${{ github.head_ref }}

      - name: Get commit message
        run: |
          readonly local msg=$(git log -1 --pretty=format:"%s")
          echo "COMMIT_MESSAGE=$msg" >> $GITHUB_ENV

      - name: Install xkcd font
        run: |
          sudo apt install fonts-humor-sans

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install tox via pipx
        run:
          python -m pip install --upgrade pip pipx-in-pipx
          pipx install tox

      - name: Prepare student book
        run: |
          tox run -e prepare

      - name: Run jupyter notebooks
        run: |
          tox run -e run

      - name: Build jupyter book
        run: |
          tox run -e verify
          tox run -e build

      - name: Commit book
        run: |
          pipx install ghp-import
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          ghp-import -n -c "compneuro.neuromatch.io" -m "Update course book" book/_build/html
          git checkout -f gh-pages

      - name: Publish to gh-pages
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
